version: ‘3’ # version of docker-compose
services: # defining service/s
  web: # name of the service
    image: nodejs/hello # image named given
    build: . # directory what to build, here it is root directory
    ports:
      - "3000:3000" # defining port for our app